from __future__ import annotations

import csv
import shutil
from datetime import date, timedelta
from pathlib import Path


START_DATE = date(2026, 7, 6)
END_DATE = date(2026, 10, 3)
CSV_HEADER = [
    "date",
    "day_number",
    "platform",
    "content_format",
    "topic_title",
    "hook_line",
    "key_points",
    "cta",
    "repurpose_notes",
    "pillar",
]
ALLOWED_PLATFORMS = {"YouTube", "Instagram", "TikTok", "Substack"}
ALLOWED_PILLARS = {
    "longevity protocols & N=1 experiments",
    "health-tech & tools",
    "founder journey/build-in-public",
    "science explainers",
}
REPO_ROOT = Path(__file__).resolve().parent
CSV_PATH = REPO_ROOT / "content_calendar_90_days.csv"
OUTPUT_DIR = Path("/home/user/output")
OUTPUT_PATH = OUTPUT_DIR / "content_calendar_90_days.csv"


ENTRIES = [
    (0, 0, "Instagram", "carousel", "Why I'm Running My Health Like a Startup", "Most health creators have time, chefs, and staff. I have investor meetings, red-eyes, and a dashboard.", "The project is a public N=1 with weekly data drops; every protocol gets an evidence grade, cost, and time score; founder constraints matter as much as ideal physiology", "Comment `FOUNDER` if you want the template for the metrics dashboard.", "Turn the opening slide into a TikTok cold open; expand the manifesto into the Week 1 Substack intro.", "founder journey/build-in-public"),
    (0, 1, "TikTok", "TikTok", "The Founder Health Problem No One Talks About", "The hidden reason founders feel terrible isn't discipline. It's context switching plus random wake times.", "Startup stress creates inconsistent sleep pressure; caffeine can hide the pattern but not fix it; I am testing health systems that survive launch weeks", "Follow for the 30-day baseline before I start changing anything.", "Use the strongest line as an IG Reel hook; cite the sleep regularity angle in YouTube intro.", "founder journey/build-in-public"),
    (0, 2, "YouTube", "long-form video", "My Full Founder Health Baseline: Labs, Wearables, Sleep, and Glucose", "I measured everything before changing anything. Here's my real founder baseline dashboard.", "Walk through bloodwork, CGM, HRV, and sleep metrics; show the dashboard architecture and baseline hypotheses; explain what success and failure will look like over 90 days", "Subscribe and reply with the metric you want me to expose publicly every week.", "Clip three TikToks from the dashboard reveal; pull the biomarker table into an IG carousel.", "health-tech & tools"),
    (0, 2, "Instagram", "Reel", "My Baseline Dashboard in 30 Seconds", "Before supplements, hacks, or ice baths, I needed one brutal thing: a baseline that doesn't lie.", "Show dashboard panes for sleep, HRV, glucose, and training; explain why trends beat anecdotes; tease the first experiment starting next week", "Send this to a founder who tracks revenue better than recovery.", "Reuse the screen recording for a TikTok with on-screen captions; screenshot frames for Stories.", "health-tech & tools"),
    (0, 3, "Substack", "Substack essay", "The Baseline Memo: How I'm Auditing My Health Like a Seed-Stage Company", "Most people start health optimization with a stack. I'm starting with instrumentation and a falsifiable memo.", "Publish baseline metrics and hypotheses; define evidence grading and confidence levels; outline how founder budget and founder calendar shape every decision", "Subscribe for the raw charts and the weekly experiment notes.", "Use the hypothesis section as a Linked-style IG carousel; quote one paragraph in the community tab.", "founder journey/build-in-public"),
    (0, 3, "TikTok", "TikTok", "3 Biomarkers I'm Tracking Before I Buy Anything", "Stop buying longevity toys before you know these three numbers.", "Resting heart rate, sleep regularity, and fasting glucose are cheap starting signals; each metric maps to a concrete behavior; expensive tools only help if the basics move", "Comment `METRICS` and I'll post the founder scorecard.", "Turn each biomarker into one IG Story card; expand into the budget-stack YouTube setup later.", "science explainers"),
    (0, 4, "Instagram", "carousel", "My $200 Founder Health Baseline Stack", "I wasted months thinking optimization had to be expensive. My actual baseline stack cost less than one airport dinner in SF.", "List low-cost tools and why each made the cut; show what I skipped and why; rank every item by evidence, cost, and friction", "Save this for your next health purchase decision.", "Convert the ranking to a TikTok voiceover; use slides in the Week 10 stack series.", "longevity protocols & N=1 experiments"),
    (0, 4, "TikTok", "TikTok", "I Almost Bought the Wrong Longevity Tests", "I almost spent $600 on flashy tests before realizing two boring labs would answer the real question.", "Explain what premium tests did not add at baseline; show the decision rule for useful data; frame testing around actionability not novelty", "Follow for the $200 version that actually changed my plan.", "Use the confession as an IG Reel; fold the cost breakdown into the bloodwork budget arc.", "health-tech & tools"),
    (0, 5, "Instagram", "Story", "Sunday Founder Recovery Reset", "My best health intervention this week cost $0 and happened on Sunday night.", "Preview sleep schedule lock-in; show meal prep, calendar cleanup, and morning-light reminders; connect recovery planning to Monday output", "DM `RESET` if you want the Sunday checklist.", "Bundle clips into a weekly recap Reel; reference the checklist in Substack PS.", "founder journey/build-in-public"),
    (0, 5, "TikTok", "TikTok", "What Demo Day Did to My Morning Glucose", "My fasting glucose after demo day looked like I ate cake at midnight. I didn't.", "Stress can move glucose without obvious food changes; founder pressure shows up in metabolic data; baseline week already exposed one invisible cost of adrenaline", "Follow for the chart after a low-stress weekend.", "Use the graph as an IG carousel slide; revisit it in the fundraising biometrics arc.", "longevity protocols & N=1 experiments"),

    (1, 0, "Instagram", "carousel", "Baseline Bloodwork: The 8 Markers That Actually Matter First", "If your blood panel has 70 numbers but no next action, it's content, not operations.", "Highlight ApoB, HbA1c, fasting glucose, ferritin, vitamin D, triglycerides, ALT, and hs-CRP; explain why each matters to a busy founder; tie each marker to one controllable lever", "Save this before your next annual exam.", "Use each marker as a one-slide Story; turn the list into a TikTok with text overlays.", "science explainers"),
    (1, 1, "TikTok", "TikTok", "Everyone Is Wrong About Founder Fatigue", "Everyone blames hustle. My baseline says irregular sleep timing is the first fire to put out.", "Show the regularity score gap; explain why total sleep alone is misleading; announce the 30-day sleep-regularity experiment", "Follow for daily charts once the experiment starts.", "Recut as an IG Reel; reference the same chart in the YouTube experiment setup.", "longevity protocols & N=1 experiments"),
    (1, 2, "YouTube", "long-form video", "The 30-Day Sleep Regularity Experiment I'm Running During Startup Chaos", "I did not pick the perfect month to fix sleep. That's exactly why this test matters.", "Define the hypothesis and success metrics; show rules for bedtime, wake time, caffeine, and late-night work; explain how I will handle travel, launches, and missed targets", "Subscribe if you want the day-30 data, not just the plan.", "Clip the hypothesis and rule set into short vertical videos; chart becomes IG carousel material.", "longevity protocols & N=1 experiments"),
    (1, 2, "Instagram", "Reel", "The Sleep Rule I'm Testing First", "The first rule in my founder sleep experiment is boring enough to work: same wake time, even after late nights.", "Explain why wake time anchors circadian rhythm; show the founder tradeoff versus sleeping in; share the metric dashboard that will judge success", "Comment `SLEEP` if you want the experiment rules.", "Use the wake-time explanation for TikTok captions; link to the full YouTube protocol.", "science explainers"),
    (1, 3, "Substack", "Substack essay", "Experiment Design: Sleep Regularity Under Real Startup Conditions", "A good health experiment should survive a product fire, not require a retreat center.", "Publish the exact protocol and exception rules; define primary and secondary endpoints; note what could confound the results and how I will log it", "Subscribe to get the weekly raw data screenshots.", "Use the protocol table in an IG carousel; pull one methods section into the YouTube description.", "longevity protocols & N=1 experiments"),
    (1, 3, "TikTok", "TikTok", "The 2-Minute Founder Sleep Audit", "Before you buy magnesium, answer this: do you wake up at the same time three days in a row?", "Walk through a simple regularity check; show why bedtime is less predictive than people think; connect inconsistency to mood and glucose swings", "Send this to the founder who says they're 'fine on six hours.'", "Port the audit questions into IG Stories with polls; mention the audit in the Substack footer.", "science explainers"),
    (1, 4, "Instagram", "carousel", "My Sleep Experiment Scoreboard", "If I can't measure it from my phone in 10 seconds, I won't sustain it during a hard week.", "Show daily scoreboard fields for bedtime, wake time, caffeine cutoff, HRV, and subjective energy; explain green-yellow-red thresholds; demonstrate how friction kills compliance", "Save this if you want to build your own scorecard.", "Turn the scoreboard walkthrough into a screen-recorded TikTok; reuse asset in later results posts.", "health-tech & tools"),
    (1, 4, "TikTok", "TikTok", "The Cheap Sleep Fix I Ignored for Years", "The $2 fix that beats every sleep gadget in my apartment is blackout tape on one LED.", "Explain light leakage and sleep continuity; show the tiny fix with absurd ROI; stress low-cost, evidence-graded interventions first", "Follow for more anti-gadget founder fixes.", "Use the before/after bedroom shot in an IG Reel; bundle with the budget stack series.", "longevity protocols & N=1 experiments"),
    (1, 5, "Instagram", "Story", "Week 1 Check-In: Missed Targets and Why", "I missed my sleep target twice in the first week. That's the useful part.", "Share the missed-target log; note late customer call and social dinner as stress tests; explain how I classify a protocol as fragile or robust", "Reply with the excuse that breaks your routine most often.", "Repost the best reply in Stories; use the failure log in the day-30 retrospective.", "founder journey/build-in-public"),
    (1, 5, "TikTok", "TikTok", "Founders Don't Need Perfect Sleep. They Need Recoverable Sleep.", "Stop chasing perfect sleep. Chase a system that recovers fast after chaos.", "Define recovery speed as the operating metric; show why perfection breaks under startup volatility; tease the recovery stack framework", "Follow for the dashboard after my first bad night test.", "Use the line as an IG Reel title; expand the concept in the Founder Recovery Stack essay.", "founder journey/build-in-public"),

    (2, 0, "Instagram", "carousel", "Sleep Experiment Day 7: What Moved First", "Seven days in, the first thing that changed wasn't sleep duration. It was how destroyed I felt at 2 p.m.", "Show early energy and focus changes; note which metrics have not moved yet; explain why lagging biomarkers require patience", "Save this if you quit experiments too early.", "Use the 2 p.m. energy insight as a TikTok opener; chart goes into Substack recap.", "longevity protocols & N=1 experiments"),
    (2, 1, "TikTok", "TikTok", "My Oura HRV Went Up After a Worse Night", "My HRV improved after a worse night of sleep. Here's why single-night interpretations are dangerous.", "Explain noise versus signal; point out adaptation, timing, and measurement variability; reinforce the need for weekly averages", "Comment `DATA` if you want the dashboard formula.", "Make this a data-myth IG Reel; reference the same caveat in YouTube.", "health-tech & tools"),
    (2, 2, "YouTube", "long-form video", "One Week Into the Sleep Experiment: Real Founder Data, Not Wellness Vibes", "I have enough data to be dangerous and just enough humility to show where I could be wrong.", "Review week-one trends across HRV, energy, glucose, and consistency; explain what I expected versus what happened; show how I separate anecdotes from directional movement", "Subscribe for the day-30 result and the inevitable mistake log.", "Cut a mistake-confession short and a chart-explainer short; reuse tables on Instagram.", "longevity protocols & N=1 experiments"),
    (2, 2, "Instagram", "Reel", "Why My Dashboard Uses Weekly Averages", "The fastest way to fool yourself is to react emotionally to one pretty graph.", "Show a daily spike versus weekly trend; explain false positives in self-tracking; connect patience to better decisions", "Share this with someone who panic-buys supplements after one bad night.", "Turn the trend graphic into a TikTok whiteboard; embed screenshot in Substack.", "health-tech & tools"),
    (2, 3, "Substack", "Substack essay", "Week 1 Data Dump: Sleep Regularity, Confidence Levels, and What I Still Don't Know", "Most N=1 content shows the result. The useful part is publishing uncertainty while the experiment is still alive.", "Share charts and confidence framing; list confounders from work stress and meals; explain why the current signal is promising but not conclusive", "Subscribe if you want the raw CSV snippets and methodology notes.", "Use one uncertainty line as a TikTok contrarian hook; spin the charts into an IG carousel.", "founder journey/build-in-public"),
    (2, 3, "TikTok", "TikTok", "Stop Reading Wearables Like Horoscopes", "If your readiness score changes your mood more than your training plan, the device is running you.", "Explain why scores should inform not dictate; show the dashboard context needed around a wearable score; encourage behavior-first interpretation", "Follow for my Oura vs Whoop benchmark next month.", "Reuse as an IG Reel; cite the line in the wearable benchmark setup video.", "health-tech & tools"),
    (2, 4, "Instagram", "carousel", "The Founder Recovery Stack v1", "I named the system because vague advice doesn't survive a product sprint.", "Stack includes consistent wake time, light, movement, meal timing, and caffeine cutoff; each layer is ranked by effort and likely impact; the stack is designed for under 30 total minutes of friction", "Comment `STACK` if you want the one-page version.", "Convert each layer into a standalone TikTok over the next month; diagram becomes a YouTube chapter graphic.", "longevity protocols & N=1 experiments"),
    (2, 4, "TikTok", "TikTok", "The 10-Minute Walk That Flattened My Afternoon Crash", "The cheapest intervention in my experiment was a 10-minute post-lunch walk. It hit harder than any supplement I own.", "Show glucose and energy response; connect walking to founder afternoon productivity; stress cost-to-benefit ratio", "Save this and test it tomorrow after lunch.", "Recreate as an IG Reel with glucose overlay; include chart in the budget stack arc.", "longevity protocols & N=1 experiments"),
    (2, 5, "Instagram", "Story", "Missed Night, Honest Log", "Last night broke the protocol. I'm posting it because that's the point of doing this in public.", "Show the late-night work block, wake time, and next-day impact; explain how exceptions are logged; remind viewers that transparent misses make the dataset stronger", "Reply if you want the exact exception template.", "Use the log screenshot in Substack appendix; turn the confession into a TikTok voiceover.", "founder journey/build-in-public"),
    (2, 5, "TikTok", "TikTok", "What I Got Wrong About Sleep Supplements", "I thought magnesium would save a chaotic schedule. It turns out timing discipline matters more than capsule optimism.", "Explain why environment and schedule came first; note supplements as second-order levers; frame evidence and friction honestly", "Follow for the final ranking once the month ends.", "Use as an IG Reel and later fold into the supplement tier list.", "science explainers"),

    (3, 0, "Instagram", "carousel", "Travel Week Protocol: How I'm Protecting the Sleep Experiment on the Road", "A protocol that only works at home is not a founder protocol.", "Show travel rules for wake time, light, caffeine, and meals; define minimum viable compliance; explain what data I expect to degrade", "Save this before your next flight.", "Turn airport clips into a TikTok montage; expand into a Substack section on robust systems.", "founder journey/build-in-public"),
    (3, 1, "TikTok", "TikTok", "Airport Mornings Wreck More Metrics Than Red-Eyes", "The sneaky killer of founder recovery isn't the flight. It's the airport breakfast plus no sunlight.", "Explain circadian disruption from travel routines; connect food timing and light exposure; show the countermeasures I actually use", "Comment `TRAVEL` if you want the checklist.", "Convert the checklist into an IG Story sequence; reference the same point in YouTube mid-experiment recap.", "science explainers"),
    (3, 2, "YouTube", "long-form video", "Travel Week Stress Test: Can My Sleep Protocol Survive Flights and Investor Dinners?", "This is the week most wellness advice dies. I wanted to know if mine would too.", "Show travel week data compared with home baseline; evaluate which rules held and which failed; explain what makes a protocol operational under founder pressure", "Subscribe for the final day-30 scoreboard and the full failure analysis.", "Clip a failure moment for TikTok; use comparison charts in an IG carousel.", "founder journey/build-in-public"),
    (3, 2, "Instagram", "Reel", "My Hotel Room Sleep Setup in 20 Seconds", "The hotel-room version of my protocol fits in a backpack and costs less than room service fries.", "Show blackout strategy, temperature hack, eye mask, and wake-time anchor; emphasize portability and simplicity; compare this to expensive biohacker travel kits", "Send this to the frequent flyer founder in your group chat.", "Reuse the packing shots for TikTok; list the items in Substack footnotes.", "longevity protocols & N=1 experiments"),
    (3, 3, "Substack", "Substack essay", "Travel Week Field Notes: Designing Recovery for Imperfect Conditions", "The real test of a health system is not whether it works in ideal conditions. It's whether it degrades gracefully.", "Publish travel-week charts and exception logs; explain robust versus fragile interventions; outline what I would change in protocol v2", "Subscribe for the final day-30 retrospective and raw graphs.", "Pull the robust-versus-fragile framework into an IG carousel; quote the thesis in a TikTok.", "founder journey/build-in-public"),
    (3, 3, "TikTok", "TikTok", "Stop Chasing 8 Hours on Travel Days", "Stop trying to manufacture perfect sleep on travel days. Protect wake time and next-day light first.", "Explain prioritization under constraints; show why a smaller number of key levers beats a bloated routine; connect to founder calendars", "Follow for the day-30 results after the travel week stress test.", "Turn this into an IG Reel with priority ranking text; cite it in YouTube outro.", "science explainers"),
    (3, 4, "Instagram", "carousel", "The Deep Work Glucose Curve", "My best coding block this week happened when my glucose curve looked boring.", "Define the Founder Deep Work Glucose Curve; compare stable versus spiky mornings; connect meal timing to concentration and meeting quality", "Save this if your 11 a.m. focus disappears every day.", "Use the chart as a TikTok data reveal; expand the framework later in a YouTube nutrition episode.", "longevity protocols & N=1 experiments"),
    (3, 4, "TikTok", "TikTok", "The Breakfast That Made My Investor Calls Worse", "A 'healthy' breakfast gave me the worst glucose swing of the week and my least sharp investor call.", "Show the meal and the spike; explain why labels like healthy are not precise enough; frame food around your own response data", "Comment `CGM` if you want more founder food experiments.", "Reuse meal footage in Instagram Reel; mention the result in Substack notes.", "longevity protocols & N=1 experiments"),
    (3, 5, "Instagram", "Story", "Week 3 Stress Test Scoreboard", "Travel week did exactly what it was supposed to do: expose the weak links.", "Show green and red checkmarks across each rule; summarize what survived; ask followers which failure looked most familiar", "Vote in the poll for the protocol rule I should keep or cut.", "Compile poll results into next week's Reel; cite them in Substack intro.", "founder journey/build-in-public"),
    (3, 5, "TikTok", "TikTok", "Why My Protocol Has a 'Minimum Viable Night' Rule", "The reason most health plans fail is they have no bad-night version.", "Define the minimum viable night rule; show the 3 behaviors I protect when the day goes sideways; tie resilience to consistency", "Follow if you want protocol templates built for real workweeks.", "Use as an IG Reel and a YouTube chapter on protocol design.", "founder journey/build-in-public"),

    (4, 0, "Instagram", "carousel", "Day 21 Sleep Data: The Signal Is Finally Clear", "Three weeks in, the chart stopped arguing with me.", "Show trend lines for wake consistency, midday energy, and resting heart rate; explain why confidence improved; note what still didn't move much", "Save this if you're deciding whether to stick with a habit another week.", "Use the clearest chart as a TikTok reveal; place full table in Substack.", "longevity protocols & N=1 experiments"),
    (4, 1, "TikTok", "TikTok", "My HRV Didn't Explode. My Focus Did.", "The biggest win from fixing sleep wasn't a sexy biomarker. It was fewer useless afternoons.", "Contrast vanity metrics with operating metrics; show what improved in work quality and energy; reinforce a founder-centered definition of success", "Follow for the final result video next week.", "Use the line as an IG Reel title; quote it in the YouTube intro.", "founder journey/build-in-public"),
    (4, 2, "YouTube", "long-form video", "Sleep Experiment Midpoint: What Improved, What Didn't, and What I'm Changing", "Halfway through, I don't need motivation. I need an honest protocol update.", "Review midpoint results and surprises; show one protocol change and justify it with data; discuss why some popular sleep tactics remain out of the plan", "Subscribe for the final day-30 outcome and the mistake report.", "Extract one clip on protocol changes for TikTok; use the score table in Instagram.", "longevity protocols & N=1 experiments"),
    (4, 2, "Instagram", "Reel", "The Mid-Experiment Change I Didn't Want to Make", "I wanted the protocol to stay clean. The data forced me to change one rule.", "Explain the modification and why it was necessary; show the tradeoff between rigor and practicality; keep the experiment transparent", "Comment if you'd keep the rule or cut it.", "Reuse as a TikTok debate-style clip; expand reasoning in Substack.", "founder journey/build-in-public"),
    (4, 3, "Substack", "Substack essay", "Midpoint Memo: Updating an N=1 Without Breaking the Experiment", "Changing a protocol midstream can ruin the test. Refusing to change can ruin the relevance.", "Explain the reasoning for one protocol adjustment; publish before-and-after decision criteria; discuss what remains comparable and what becomes exploratory", "Subscribe for the day-30 data package and postmortem.", "Use the decision criteria table in an IG carousel; quote the thesis in Stories.", "founder journey/build-in-public"),
    (4, 3, "TikTok", "TikTok", "The Sleep Metric I Care About More Than Duration", "The sleep metric I care about most right now is regularity, not total hours.", "Define sleep regularity in plain English; show why it predicts how my days feel under stress; debunk the 'just sleep more' oversimplification", "Save this if your schedule is messy but non-negotiable.", "Adapt into an IG carousel explanation; reference metric in YouTube chapters.", "science explainers"),
    (4, 4, "Instagram", "carousel", "What a Good Founder Experiment Log Looks Like", "If you can't explain what changed, your data is decoration.", "Show inputs, outputs, confounders, and notes fields; explain why honest logs beat perfect-looking charts; invite people to separate evidence from storytelling", "Comment `LOG` if you want the template fields.", "Use the log screen in TikTok; include the template in Substack resources.", "health-tech & tools"),
    (4, 4, "TikTok", "TikTok", "How I Track Confounders Without Becoming Insufferable", "You do not need a spreadsheet for every sip of water. You need a log that catches the big lies.", "Show the few confounders I track consistently; explain why over-logging kills adherence; connect signal quality to simplicity", "Follow for the full dashboard walkthrough after day 30.", "Repurpose the log examples into an IG Story quiz; cite in the tools series.", "health-tech & tools"),
    (4, 5, "Instagram", "Story", "Midpoint Charts, Raw and Unfiltered", "Posting the ugly charts matters more than posting the flattering ones.", "Share screenshots of flat or noisy metrics; note what has not improved; reinforce transparency as the brand promise", "Reply with the metric you want me to unpack next week.", "Turn the requested metric into the next TikTok Q&A; mention top replies in Substack.", "founder journey/build-in-public"),
    (4, 5, "TikTok", "TikTok", "The Problem With 'Feel Better' Health Content", "If a protocol 'works' but you never define success, you're just collecting placebo with better lighting.", "Argue for measurable endpoints; show my current success metrics; frame why founders need clearer definitions than vibes", "Follow for the final day-30 scoreboard.", "Use as a contrarian IG Reel; lead the YouTube results episode with this line.", "science explainers"),

    (5, 0, "Instagram", "carousel", "Day 30 Results: My Founder Sleep Experiment Scorecard", "I did the sleep experiment for 30 days. Here's what happened to my energy, HRV, glucose, and schedule compliance.", "Publish final metrics and percent changes; separate strong signals from weak ones; show where the protocol failed under pressure", "Save this if you're designing your own sleep test.", "Turn each result into a TikTok clip; use the scorecard in the YouTube thumbnail layout.", "longevity protocols & N=1 experiments"),
    (5, 1, "TikTok", "TikTok", "My Best Sleep Result Wasn't More Sleep", "The biggest win from 30 days wasn't sleeping longer. It was making late nights less expensive.", "Explain improved recovery after bad nights; show consistency effects on next-day energy; highlight protocol resilience over perfection", "Comment `RESULTS` if you want the full breakdown.", "Use as an IG Reel highlight; reference it in the Substack retrospective.", "longevity protocols & N=1 experiments"),
    (5, 2, "YouTube", "long-form video", "I Fixed My Sleep for 30 Days During Startup Chaos: Full Results and What I'd Actually Keep", "I did the experiment in the worst possible conditions for wellness content. That's why the results matter.", "Walk through final data and founder-relevant outcomes; rank which protocol elements were worth the effort; admit what I expected that never materialized", "Subscribe for the next experiment and the wearable benchmark series.", "Cut a best-result short, a biggest-miss short, and a budget-takeaway short; convert ranking into an IG carousel.", "longevity protocols & N=1 experiments"),
    (5, 2, "Instagram", "Reel", "The One Sleep Habit I'd Keep If I Had to Drop Everything Else", "If I had to keep one habit from the entire experiment, it's not the supplement. It's the schedule anchor.", "Name the single most valuable behavior; explain the evidence from this N=1; keep the recommendation grounded in cost and consistency", "Send this to someone drowning in sleep advice.", "Use the clip as a TikTok; make the ranking a Story follow-up.", "longevity protocols & N=1 experiments"),
    (5, 3, "Substack", "Substack essay", "Sleep Experiment Retrospective: Wins, Failures, Confounders, and Confidence", "The useful version of a self-experiment includes what failed, what stayed noisy, and what I'm not claiming.", "Publish full retrospective with confidence levels; separate causal confidence from speculation; note how founder stress affected the outcome", "Subscribe if you want the downloadable experiment template for your own N=1.", "Use the 'what I'm not claiming' section in an IG carousel; quote a failure line in TikTok.", "founder journey/build-in-public"),
    (5, 3, "TikTok", "TikTok", "What I Got Wrong Before Running My First Real N=1", "I thought the hard part would be discipline. The hard part was designing a protocol that survived reality.", "Reflect on experiment design, not just outcome; explain what changed in my thinking; set up the next arc on wearables", "Follow for Oura vs Whoop vs Apple Watch from a founder's perspective.", "Reuse as an IG Reel; transition into YouTube wearable benchmark intro.", "founder journey/build-in-public"),
    (5, 4, "Instagram", "carousel", "Sleep Experiment ROI Ranked by Cost and Time", "Not all sleep interventions deserve equal oxygen. Here's the founder ROI ranking after 30 days.", "Rank interventions by evidence, cost, time, and observed impact; call out overrated items; explain why cheap basics won", "Save this before you buy another sleep product.", "Turn each rank into a TikTok mini-review; reuse ranking in a future YouTube tier list.", "longevity protocols & N=1 experiments"),
    (5, 4, "TikTok", "TikTok", "The $2 Fix That Beat Every Sleep Gadget I Tried", "The $2 fix that beat every sleep gadget I own is still embarrassingly analog.", "Reveal the simple fix and why it worked; compare cost and friction to gadgets; push the anti-concierge positioning", "Follow for the wearable benchmark next week.", "Use the same reveal in an IG Reel; mention the fix in email PS.", "longevity protocols & N=1 experiments"),
    (5, 5, "Instagram", "Story", "Postmortem Poll: What Should I Test Next?", "I finished the first experiment. Now I'm choosing the next one based on impact, cost, and what founders actually struggle with.", "Offer options like wearables, budget supplements, and glucose routines; ask for audience priorities; tie choice to brand thesis", "Vote in the Story and I'll publish the scoring matrix.", "Share poll results in TikTok comments video; cite them in the next Substack intro.", "founder journey/build-in-public"),
    (5, 5, "TikTok", "TikTok", "What a Transparent Health Brand Should Publish", "If you build a health brand on data, you should publish your misses too.", "Define transparency standards I want to keep; explain why raw logs build trust; challenge polished-but-unfalsifiable content", "Follow if you want more open-source-style health experiments.", "Repurpose as a founder-philosophy IG Reel; use soundbite in YouTube intro.", "founder journey/build-in-public"),

    (6, 0, "Instagram", "carousel", "Wearable Benchmark Setup: Oura vs Whoop vs Apple Watch", "I'm not asking which wearable is coolest. I'm asking which one earns a founder's wrist space.", "Show evaluation criteria for sleep, recovery, workouts, battery, and data export; explain why founder use-case matters; preview the testing window", "Save this if you're deciding between wearables right now.", "Use the criteria slides as a TikTok voiceover; expand each criterion in YouTube.", "health-tech & tools"),
    (6, 1, "TikTok", "TikTok", "Stop Asking 'Which Wearable Is Best?'", "The better question is: which wearable is best for the decision you actually need to make?", "Different tools win different jobs; founder use-cases include travel, meetings, workouts, and data portability; show my benchmark scoring categories", "Comment `WEARABLE` and I'll post the scorecard.", "Use as an IG Reel opener; link to the full benchmark setup video.", "health-tech & tools"),
    (6, 2, "YouTube", "long-form video", "Oura vs Whoop vs Apple Watch: The Founder Benchmark Setup", "I bought three wearables so I could stop guessing and start benchmarking.", "Explain the test design and evaluation framework; show how I will compare data fidelity and practical friction; define which founder scenarios matter most", "Subscribe for the first benchmark results and comment the metric you care about most.", "Cut one clip on scoring criteria and one on data export; turn the matrix into IG carousel slides.", "health-tech & tools"),
    (6, 2, "Instagram", "Reel", "My Wearable Test Bench", "This is the least aesthetic video you'll see today: three wearables, one founder, and a giant spreadsheet.", "Show the devices and dashboard; explain what counts as a win in this benchmark; frame practical usefulness over brand hype", "Send this to the friend still arguing from YouTube comments only.", "Reuse the test-bench footage on TikTok; include screenshot in Substack.", "health-tech & tools"),
    (6, 3, "Substack", "Substack essay", "Benchmark Design Notes: How to Compare Wearables Without Fooling Yourself", "Most wearable reviews are lifestyle impressions with affiliate links. I wanted a repeatable benchmark.", "Publish the benchmark methodology and scoring rubric; define measurement versus product UX criteria; explain where subjective judgment still enters", "Subscribe for the raw scoring sheets as the series progresses.", "Turn the rubric into an IG carousel; quote the affiliate-link line in a TikTok.", "health-tech & tools"),
    (6, 3, "TikTok", "TikTok", "The Wearable Feature I Care About More Than Sleep Score", "The wearable feature I care about most isn't the score. It's whether I can get the data out.", "Explain data export and integration value; connect API or CSV access to real experimentation; show why closed dashboards limit learning", "Follow for the dashboard build once the benchmark is done.", "Use the data-export point in an IG carousel; revisit it in the dashboard build video.", "health-tech & tools"),
    (6, 4, "Instagram", "carousel", "Founder Use Cases That Most Wearable Reviews Ignore", "Most wearable reviews don't ask whether the device helps after a red-eye, a board meeting, or a coding sprint.", "List founder-specific scenarios for benchmarking; explain why generic athlete reviews miss them; show how context changes device value", "Save this if your life looks nothing like a fitness influencer's.", "Turn each use case into a TikTok prompt; reuse in YouTube chapters.", "founder journey/build-in-public"),
    (6, 4, "TikTok", "TikTok", "Why Battery Life Matters More Than Features for Founders", "If your wearable dies during travel week, every clever feature becomes fiction.", "Show founder calendar constraints; compare battery friction to real adherence; argue that reliable capture beats occasional richness", "Comment with the device that failed you first.", "Use as an IG Reel with travel visuals; mention in Substack scoring notes.", "health-tech & tools"),
    (6, 5, "Instagram", "Story", "Benchmark Week Poll: Which Device Do You Trust Most?", "Before I post results, I want to know which brand already owns your assumptions.", "Run poll for Oura, Whoop, and Apple Watch; ask why people trust each device; collect hypotheses to test against actual data", "Vote and I'll compare the poll to the final scores.", "Use poll results in TikTok comments reaction; cite them in the final benchmark recap.", "health-tech & tools"),
    (6, 5, "TikTok", "TikTok", "The Mistake I Made Buying Wearables the First Time", "I bought my first wearable for motivation. I should have bought it for decisions.", "Explain the difference between inspiration and instrumentation; show how use-case clarity changes purchase decisions; tie back to founder budgets", "Follow for the first real benchmark results next week.", "Reuse as an IG Reel; quote the line in the budget stack series.", "health-tech & tools"),

    (7, 0, "Instagram", "carousel", "Sleep Tracking Accuracy: First Wearable Benchmark Scores", "The first surprising result from my benchmark is that the prettiest dashboard did not win on trust.", "Share early scores for sleep consistency and interpretation; explain where the devices diverged; show confidence and caveats", "Save this if sleep tracking is your main reason for buying one.", "Convert each score into a TikTok chart reveal; reference table in YouTube results video.", "health-tech & tools"),
    (7, 1, "TikTok", "TikTok", "One Wearable Called Me Recovered. Another Called Me Cooked.", "Two devices looked at the same body and gave me opposite advice. Here's why that matters.", "Compare conflicting readiness outputs; explain how algorithms and input assumptions differ; argue for trend literacy over blind trust", "Follow for the full Oura vs Whoop vs Apple Watch breakdown.", "Use same split-screen in IG Reel; cite the contradiction in Substack.", "health-tech & tools"),
    (7, 2, "YouTube", "long-form video", "Oura vs Whoop vs Apple Watch for Sleep and Recovery: Real Founder Results", "After weeks of wearing all three, I finally know which one helps me make better decisions.", "Compare sleep, recovery, battery, and practical usefulness; show where each device wins and loses; make founder-specific recommendations by use-case", "Subscribe for the workout and stress benchmark next week.", "Clip one winner reveal and one contradiction reveal for short-form; turn the scoring table into an IG carousel.", "health-tech & tools"),
    (7, 2, "Instagram", "Reel", "The Sleep Tracking Winner for Busy Founders", "If sleep tracking is the only job you care about, one device clearly earned the recommendation.", "Name the winner and the runner-up; explain the deciding criteria; keep the recommendation tied to practical constraints", "Comment with the device you're using now.", "Use the same footage in TikTok; summarize details in Stories.", "health-tech & tools"),
    (7, 3, "Substack", "Substack essay", "Benchmark Round 1: Sleep, Recovery, and the Problem With Readiness Scores", "A single recovery score feels useful until three devices disagree and your calendar doesn't care.", "Publish the score table and notes; explain interpretation pitfalls; recommend a decision framework instead of blind score obedience", "Subscribe for Round 2: workouts, stress, and data pipelines.", "Use the decision framework as an IG carousel; quote the strongest line in TikTok.", "science explainers"),
    (7, 3, "TikTok", "TikTok", "Stop Letting a Recovery Score Cancel Your Workout", "A readiness score can be input. It should not be your boss.", "Explain how I use recovery scores in context; show examples of when I ignore them; connect to training consistency and work demands", "Save this for the next time your wearable scares you.", "Adapt to IG Reel; use one example in the YouTube follow-up.", "science explainers"),
    (7, 4, "Instagram", "carousel", "The Wearable Data I Actually Log Manually", "Even with three devices on my body, there are still four things I trust myself to log by hand.", "List subjective energy, unusual stressors, meal timing, and training intent; explain why context still matters; show how manual notes rescue device data", "Save this if your dashboard feels complete but somehow useless.", "Turn each manual field into a TikTok tip; reuse notes screenshot in YouTube.", "health-tech & tools"),
    (7, 4, "TikTok", "TikTok", "The Wearable Metric That Most Closely Matched My Actual Day", "One metric tracked how I really felt better than the flashy composite scores.", "Reveal the metric and why it matched better; explain the link to daily function; compare it with the metrics that overpromised", "Follow for the workout benchmark next.", "Reuse as an IG Reel and mention it in Substack charts.", "health-tech & tools"),
    (7, 5, "Instagram", "Story", "Round 1 Winner Board", "The winner depends on the job. That's the whole point of benchmarking instead of fanboying.", "Share current leaders by sleep, battery, and low-friction use; remind viewers that final recommendation is scenario-specific; ask which use-case matters next", "Reply with the use-case you want scored harder in Round 2.", "Use the replies as prompts for TikTok Q&A; mention top answer in Substack.", "health-tech & tools"),
    (7, 5, "TikTok", "TikTok", "What Most Wearable Reviewers Never Show You", "Most wearable reviewers show opinions. I'm showing the scoring rubric, the misses, and the contradiction log.", "Highlight transparency and methodology; differentiate from affiliate-style reviews; reinforce the open-data brand", "Follow for the final benchmark winner after workouts and stress.", "Turn the transparency message into an IG Reel; cite it in YouTube outro.", "founder journey/build-in-public"),

    (8, 0, "Instagram", "carousel", "Workout Tracking Benchmark: Which Wearable Was Least Annoying to Lift With?", "The best training wearable is the one you stop noticing after minute five.", "Compare comfort, heart-rate usefulness, and workout logging friction; show how form factor affects adherence; keep recommendations use-case specific", "Save this if you train and code in the same day.", "Use the comfort ranking in TikTok; include full scorecard in YouTube.", "health-tech & tools"),
    (8, 1, "TikTok", "TikTok", "I Ranked 3 Wearables by Founder Annoyance", "I ranked Oura, Whoop, and Apple Watch by the metric reviewers skip: how annoying they are during a real workday.", "Evaluate notifications, charging friction, strap comfort, and screen temptation; connect annoyance to long-term adherence; give quick scores", "Comment with the device that annoys you most.", "Convert the ranking into an IG carousel; expand the rationale in Substack.", "health-tech & tools"),
    (8, 2, "YouTube", "long-form video", "Workout, Stress, and Daily Friction: The Final Wearable Benchmark", "A wearable can have great data and still lose if it makes daily life worse.", "Compare workout tracking, stress usefulness, battery, export, and annoyance; announce overall winners by founder persona; show the final scoring matrix", "Subscribe for the next arc on budget longevity stacks and low-cost testing.", "Cut one TikTok on annoyance ranking and one on final winner; turn the matrix into Instagram slides.", "health-tech & tools"),
    (8, 2, "Instagram", "Reel", "The Wearable I'd Recommend to a Fundraising Founder", "If you're fundraising, the best wearable is not the one with the most features. It's the one you'll keep wearing through chaos.", "Name the recommended device for travel-heavy stress; explain why battery and friction matter; compare briefly to alternatives", "Send this to a founder about to buy a wearable this month.", "Reuse the same recommendation as a TikTok; add details in Stories.", "health-tech & tools"),
    (8, 3, "Substack", "Substack essay", "Final Benchmark Memo: Which Wearable Earns Its Cost for Different Founder Profiles", "The right wearable depends on whether you care most about sleep, training, data export, or just not being annoyed.", "Publish persona-based recommendations; include scoring matrix and methodology caveats; explain where the benchmark remains subjective", "Subscribe for the budget-stack framework and testing-on-a-budget series.", "Use persona recommendations as an IG carousel; quote the thesis in TikTok.", "health-tech & tools"),
    (8, 3, "TikTok", "TikTok", "The Wearable Winner Depends on One Question", "Before you buy a wearable, answer this one question: what decision will it help you make tomorrow morning?", "Force the purchase decision through actionability; explain different answers for sleep, training, and stress; push back on generic 'best device' discourse", "Save this before Prime Day or your next impulsive purchase.", "Adapt into an IG Reel; reuse question in budget stack content.", "science explainers"),
    (8, 4, "Instagram", "carousel", "How I Pipe Wearable Data Into One Founder Dashboard", "The real unlock wasn't choosing a wearable. It was getting the data into one place I actually look.", "Show the dashboard layout and data sources; explain why a single pane matters; keep the stack simple and reproducible", "Comment `DASHBOARD` if you want the tool list.", "Use the screen recording in TikTok; expand with code notes in a later YouTube video.", "health-tech & tools"),
    (8, 4, "TikTok", "TikTok", "My Health Dashboard Has the Same Rule as My Startup Dashboard", "If a dashboard requires effort to understand, it's already dead.", "Explain ruthless simplicity in metrics design; show the top cards on my health dashboard; connect engineering habits to personal health tracking", "Follow for the dashboard build video and template breakdown.", "Reuse as an IG Reel; cite the rule in Substack.", "health-tech & tools"),
    (8, 5, "Instagram", "Story", "Ask Me Anything: Wearables Edition", "The benchmark is done. Now I'm answering the questions the review videos usually dodge.", "Invite questions on battery, export, accuracy, and founder use-cases; tease the next tooling build series; keep the tone practical", "Drop your question and I'll answer the best ones on TikTok.", "Use questions for a comments-response TikTok; summarize answers in Substack footnotes.", "health-tech & tools"),
    (8, 5, "TikTok", "TikTok", "The Data Export Test That Eliminated One Wearable Fast", "One wearable lost a lot of points the moment I tried to get clean data out of it.", "Show the export problem and why it matters; connect locked data to weak experimentation; reinforce builder-first evaluation", "Follow for the dashboard build and budget stack arc.", "Reuse as an IG Reel with screen capture; mention in YouTube dashboard build.", "health-tech & tools"),

    (9, 0, "Instagram", "carousel", "My $50/Month Longevity Stack Ranked by Evidence", "I don't have Bryan Johnson money. Good. It forced me to rank interventions like a real operator.", "List the monthly stack and evidence grades; separate essentials from vanity; include cost and time burden for each item", "Save this if you want a realistic starting stack.", "Turn the top three into TikTok clips; use the full table in YouTube.", "longevity protocols & N=1 experiments"),
    (9, 1, "TikTok", "TikTok", "The $2 Fix That Beats Expensive Longevity Toys", "The cheapest item in my longevity stack delivers more actual benefit than gear ten times the price.", "Reveal the low-cost intervention; compare it against common expensive purchases; explain the evidence and adherence advantage", "Comment `CHEAP` if you want the full stack.", "Reuse as an IG Reel; mention in the stack-ranking YouTube intro.", "longevity protocols & N=1 experiments"),
    (9, 2, "YouTube", "long-form video", "My Budget Founder Longevity Stack: What I'd Buy With Only $50 a Month", "If I lost every premium gadget tomorrow, this is the evidence-graded stack I'd rebuild first.", "Rank interventions by evidence, cost, and friction; show what I excluded and why; connect each item to founder outcomes like energy and recovery", "Subscribe for the under-$200 testing guide and the fundraising-stress biometrics arc.", "Cut one TikTok on top pick and one on overrated item; turn ranking into an IG carousel.", "longevity protocols & N=1 experiments"),
    (9, 2, "Instagram", "Reel", "My Number One Budget Intervention", "The best item in my budget stack is boring, cheap, and embarrassingly effective.", "Reveal the intervention and why it outranked supplements; show cost and time burden; tie it to a concrete metric improvement", "Send this to someone who thinks optimization starts at $300 a month.", "Repurpose into TikTok with price overlay; expand details in Stories.", "longevity protocols & N=1 experiments"),
    (9, 3, "Substack", "Substack essay", "The Anti-$2M Longevity Memo: How I Rank Protocols by Evidence, Cost, and Founder Friction", "A longevity protocol is not useful to me if it needs concierge logistics or a three-hour morning.", "Explain the ranking framework and its weights; publish the full stack table; argue for founder-specific practicality as a first-class criterion", "Subscribe for the upcoming testing-on-a-budget playbook.", "Use the framework as an IG carousel; quote the concierge line in TikTok.", "science explainers"),
    (9, 3, "TikTok", "TikTok", "Stop Copying Longevity Routines You Can't Sustain", "Stop copying routines built for full-time self-optimization. Build one that survives your actual calendar.", "Explain sustainability as a design constraint; show my screening questions for any protocol; differentiate inspiration from implementation", "Follow for the under-$200 test plan next.", "Reuse as an IG Reel; use the screening questions in Stories.", "founder journey/build-in-public"),
    (9, 4, "Instagram", "carousel", "Supplements I Didn't Put in My Budget Stack", "Everyone wants to know what I take. The more useful question is what I refused to include.", "List excluded supplements and the reason each missed the cut; explain weak evidence or high friction; emphasize first-order levers over capsule theater", "Save this before your next supplement order.", "Turn each exclusion into a TikTok myth-buster; reference the list in Substack.", "science explainers"),
    (9, 4, "TikTok", "TikTok", "N Supplements Ranked by Evidence, Founder Edition", "Here are five popular supplements ranked by evidence, cost, and whether a founder can use them consistently.", "Quick-rank magnesium, creatine, omega-3, vitamin D, and fancy nootropics; explain one sentence per ranking; keep claims tightly bounded", "Comment the supplement you want me to score next.", "Adapt into a multi-slide IG carousel; expand reasoning in a future YouTube tier list.", "science explainers"),
    (9, 5, "Instagram", "Story", "Stack Vote: What Should I Add or Test?", "The stack is version one. I'm collecting the strongest case for anything I left out.", "Ask viewers for candidate interventions; require evidence and cost justification; tease that weak suggestions will get rejected publicly", "Reply with your strongest case and one study if you have it.", "Turn best suggestions into a TikTok response series; mention top picks in Substack PS.", "founder journey/build-in-public"),
    (9, 5, "TikTok", "TikTok", "Why Expensive Doesn't Mean Evidence-Based", "A lot of longevity spending is just expensive uncertainty with nicer branding.", "Contrast marketing intensity with evidence quality; show how I grade interventions; reinforce the anti-hype angle", "Follow for the $200 testing guide next week.", "Reuse as an IG Reel; use the line in YouTube cold open later.", "science explainers"),

    (10, 0, "Instagram", "carousel", "The $200 Founder Testing Plan", "I wasted $3,000 chasing longevity certainty. Here's the $200 version that actually changed decisions.", "List core tests and approximate costs; explain what each test can influence; show what expensive tests I still skip", "Save this before your next lab order.", "Turn the cost breakdown into TikTok captions; use table in YouTube.", "health-tech & tools"),
    (10, 1, "TikTok", "TikTok", "I Wasted $3,000 on Longevity Tests", "I wasted $3,000 on longevity tests. The painful part is that the $200 version gave me the actionable answers.", "Confess the over-testing mistake; identify the smaller test set that mattered; explain actionability as the filter", "Follow for the full founder testing protocol.", "Reuse as an IG Reel; anchor the YouTube hook with this line.", "health-tech & tools"),
    (10, 2, "YouTube", "long-form video", "The Under-$200 Longevity Testing Stack I'd Use If I Were Starting Over", "If I had to rebuild my testing stack from zero on a founder budget, this is exactly where I'd start.", "Break down bloodwork, body comp, and simple performance testing; explain why some glamorous tests are lower priority; connect outputs to actions", "Subscribe for the fundraising-stress biometrics experiment starting next week.", "Clip one short on best-value test and one on overrated test; turn comparison table into IG carousel.", "health-tech & tools"),
    (10, 2, "Instagram", "Reel", "The One Test I'd Pay For First", "If you can only pay for one category of testing first, start with the one that changes multiple decisions at once.", "Name the priority test and explain why; show the downstream decisions it informs; keep the recommendation budget-aware", "Send this to a friend about to book random wellness labs.", "Reuse in TikTok with price overlay; link back to full YouTube episode.", "health-tech & tools"),
    (10, 3, "Substack", "Substack essay", "Testing on a Budget: The Founder Playbook for Bloodwork, DEXA, and What to Skip", "A test is only worth the money if you know what you would do differently after the result.", "Publish the decision tree for each test; show cost ranges and actionability; explain why sequencing matters more than comprehensiveness", "Subscribe for the stress-biometrics experiment design dropping next.", "Use the decision tree in an IG carousel; quote the thesis in TikTok.", "science explainers"),
    (10, 3, "TikTok", "TikTok", "The Test I Refuse to Buy Yet", "The test I'm refusing to buy right now isn't bad. It's just lower value than people pretend.", "Explain why I am postponing one popular test; compare its actionability with cheaper alternatives; reinforce sequencing over collecting", "Comment the test you think I'm underrating.", "Use as an IG Reel debate post; mention opposing cases in Stories.", "science explainers"),
    (10, 4, "Instagram", "carousel", "How I Decide Whether a Health Test Is Worth It", "Before I buy any health test, it has to pass three questions in my dashboard.", "Show questions on actionability, repeatability, and founder friction; explain how these screens prevent novelty spending; give examples", "Save this before your next wellness checkout page.", "Turn each question into a TikTok mini-lesson; use graphic in Substack resource section.", "health-tech & tools"),
    (10, 4, "TikTok", "TikTok", "The Hidden Cost of Over-Testing", "The hidden cost of too many tests isn't money. It's chasing noise instead of behavior change.", "Explain decision fatigue from excess data; show how too many numbers delay action; frame testing as a means, not identity", "Follow for the fundraising stress experiment next week.", "Adapt into an IG Reel; cite this line in the YouTube outro.", "science explainers"),
    (10, 5, "Instagram", "Story", "Budget Testing Q&A", "I'm answering the test questions people are usually too embarrassed to ask after overpaying.", "Invite questions on cost, timing, and what to repeat; keep replies practical and non-performative; tease next week's stress arc", "Drop your question and I'll answer the best ones on video.", "Use the best question in a TikTok reply; summarize FAQ in Substack footnote.", "health-tech & tools"),
    (10, 5, "TikTok", "TikTok", "The Founder Metric That Matters More Than Fancy Labs", "If your sleep, movement, and glucose behaviors are a mess, one more fancy lab will not save you.", "Challenge lab-first optimization; tie daily behavior metrics to founder execution; keep the message anti-hype but actionable", "Follow for my stress biometrics data during fundraising-style weeks.", "Reuse as an IG Reel; reference the line in the next YouTube intro.", "founder journey/build-in-public"),

    (11, 0, "Instagram", "carousel", "My HRV Dropped 40% During a High-Stress Week", "My HRV dropped hard during a founder-style stress week. Here's the dashboard and what caused it.", "Show the HRV chart and timeline; connect stressors like fundraising prep and poor meal timing; preview the recovery plan", "Save this if your body acts weird during high-pressure weeks.", "Turn the chart reveal into TikTok; expand the context in YouTube.", "founder journey/build-in-public"),
    (11, 1, "TikTok", "TikTok", "Stress Is Showing Up in My Data Faster Than I Expected", "I expected stress to show up in mood. It hit my biometrics before my brain admitted anything was wrong.", "Explain early physiological signals; show the gap between subjective perception and wearable data; set up the recovery test", "Follow for the stress-recovery protocol and results.", "Reuse as an IG Reel; quote the line in Substack.", "founder journey/build-in-public"),
    (11, 2, "YouTube", "long-form video", "Fundraising Stress Biometrics: What Startup Pressure Did to My Sleep, HRV, and Glucose", "This is the most founder-specific health video I've made because the stressor is the job itself.", "Walk through the high-stress week dashboard; explain where the biggest hits showed up; outline the recovery protocol I am testing next", "Subscribe for the recovery results and the final 90-day synthesis.", "Clip the HRV reveal and the recovery plan into short-form; turn the dashboard into Instagram slides.", "founder journey/build-in-public"),
    (11, 2, "Instagram", "Reel", "The Metric That Snitched on My Stress First", "Before I felt burnt out, one metric raised its hand and said the week was already too expensive.", "Reveal the earliest-moving metric; explain why it matters; encourage people to watch patterns before symptoms escalate", "Comment if you want the exact dashboard threshold I use.", "Reuse as a TikTok with chart overlay; add threshold graphic to Stories.", "health-tech & tools"),
    (11, 3, "Substack", "Substack essay", "Stress Week Notes: What Fundraising-Style Pressure Did to My Biomarkers", "The founder version of burnout starts as a graph before it becomes a feeling.", "Publish the stress-week timeline and charts; discuss likely drivers and confounders; define the recovery hypotheses for the next week", "Subscribe for the recovery protocol and final postmortem.", "Use the timeline as an IG carousel; quote the opening line in TikTok.", "founder journey/build-in-public"),
    (11, 3, "TikTok", "TikTok", "The Hidden Reason You're Always Tired Might Not Be Sleep", "The hidden reason you're always tired might be unresolved stress showing up in glucose and HRV, not just shorter nights.", "Link stress physiology to energy crashes; distinguish sleep quantity from recovery quality; show one chart from my week", "Follow for the recovery protocol I’m testing next.", "Convert to an IG Reel; expand the physiology in Substack.", "science explainers"),
    (11, 4, "Instagram", "carousel", "The Founder Recovery Protocol I'm Using After a Stress Spike", "After my HRV cratered, I didn't need a heroic reset. I needed a protocol I could do while still working.", "Show the recovery stack for stress weeks; rank each step by effort and likely impact; explain why drastic detox plans are unrealistic", "Save this for your next brutal workweek.", "Turn each recovery step into a TikTok; use the ranking in YouTube results.", "longevity protocols & N=1 experiments"),
    (11, 4, "TikTok", "TikTok", "Stop Trying to Biohack Your Way Out of Chronic Slack Panic", "If your nervous system is cooked, another supplement stack is not the first move.", "Push back on supplement-first stress advice; show my behavior-first recovery sequence; keep the tone practical for operators", "Share this with the founder who keeps buying calm in capsule form.", "Reuse as an IG Reel with strong captions; cite in Substack closing.", "science explainers"),
    (11, 5, "Instagram", "Story", "Stress Week Raw Notes", "This week was messy on purpose. I'm posting the notes because polished stress content is usually useless.", "Share screenshots of calendar load, sleep misses, and recovery actions; ask audience which variable they want unpacked; reinforce transparency", "Reply with the variable you want me to break down next.", "Use the top request in a TikTok Q&A; mention it in the final synthesis.", "founder journey/build-in-public"),
    (11, 5, "TikTok", "TikTok", "The Recovery Rule I Use After a Brutal Day", "After a brutal founder day, I don't ask what's optimal. I ask what's the minimum that prevents tomorrow from getting worse.", "Explain the minimum viable recovery rule; show the few actions I preserve; tie it to maintaining output under pressure", "Follow for the recovery results and final system next week.", "Repurpose as an IG Reel; use the rule in the synthesis video.", "founder journey/build-in-public"),

    (12, 0, "Instagram", "carousel", "90 Days In: The Founder Health Operating System v1", "Ninety days in, I don't have a perfect body protocol. I have a system I trust under pressure.", "Summarize the operating system layers; show what the first 90 days taught me; identify what remains uncertain and what is now default", "Save this if you want the full founder-health system in one place.", "Turn each layer into TikTok clips; use diagram in final YouTube recap.", "founder journey/build-in-public"),
    (12, 0, "TikTok", "TikTok", "The One Rule That Survived Every Experiment", "Across sleep, stress, and tools, one rule kept winning: lower friction beats cleverness.", "Summarize the operating principle; show examples from sleep, wearables, and recovery; tie it to startup operator behavior", "Follow for the final 90-day recap video tomorrow.", "Reuse as an IG Reel opener; cite the rule in Substack synthesis.", "founder journey/build-in-public"),
    (12, 1, "YouTube", "long-form video", "90 Days of Founder Health in Public: What Actually Worked, What Failed, and What's Next", "I spent 90 days treating my health like a startup project. Here's what survived contact with real life.", "Synthesize the biggest wins, failures, and tools; explain how the system changed my workdays and recovery; announce the next experiment direction", "Subscribe if you want the next 90-day experiment from day zero.", "Cut one short on biggest surprise and one on biggest mistake; use the summary graphic on Instagram.", "founder journey/build-in-public"),
    (12, 2, "Instagram", "Reel", "My Biggest Mistake From 90 Days of Tracking", "My biggest mistake wasn't missing days. It was overvaluing interesting data over actionable data.", "Confess the mistake and what it cost; show how the system changed after that realization; reinforce actionability as the filter", "Comment with the data point you obsess over most.", "Reuse as TikTok confession format; expand lesson in Substack.", "health-tech & tools"),
    (12, 2, "TikTok", "TikTok", "What 90 Days of Data Changed About My Mornings", "Ninety days of data changed my mornings more than my supplement drawer.", "Explain the morning routine changes that stuck; show how they influenced stress, focus, and recovery; keep it founder-realistic", "Save this if your mornings feel reactive instead of designed.", "Adapt as an IG Reel with routine footage; mention in YouTube recap.", "longevity protocols & N=1 experiments"),
    (12, 3, "Substack", "Substack essay", "The 90-Day Synthesis: Lessons From Running Health Like a Startup", "The point of 90 days was not to become optimized. It was to become less confused.", "Synthesize decision rules, experiment lessons, and durable defaults; explain what I now believe with high confidence; list open questions for the next cycle", "Subscribe for the next experiment and the downloadable operating system summary.", "Use the decision rules as an IG carousel; quote the thesis in TikTok.", "founder journey/build-in-public"),
    (12, 3, "Instagram", "carousel", "Five Decision Rules I Use Now for Health", "I don't need more tips. I need better rules for what earns time, money, and attention.", "List rules on actionability, friction, evidence, reversibility, and measurement; show one example for each; keep them founder-calibrated", "Save this if you want fewer health tabs open in your browser.", "Turn each rule into a TikTok clip; use the list in a community post later.", "science explainers"),
    (12, 4, "TikTok", "TikTok", "The Dashboard Card That Earned Permanent Status", "One card on my health dashboard earned permanent status because it predicts bad days before they fully land.", "Reveal the metric and threshold; explain how I use it to adjust behavior; connect it to founder recovery planning", "Follow for the next build-in-public experiment.", "Reuse as an IG Reel with dashboard screen capture; mention in Stories.", "health-tech & tools"),
    (12, 4, "Instagram", "Reel", "What I'm Testing Next After 90 Days", "The next experiment is obvious now because the first 90 days narrowed the actual bottleneck.", "Announce the next experiment theme; explain why the data points there; invite audience predictions", "Comment the outcome you think will surprise me most.", "Use as TikTok teaser; expand rationale in a YouTube community post.", "founder journey/build-in-public"),
    (12, 5, "Instagram", "Story", "Final Week AMA", "The first 90 days are done. I'm answering the toughest questions before I start the next cycle.", "Invite questions on methods, metrics, and what I would cut; offer a raw-data follow-up; keep the tone transparent", "Drop a question and I’ll answer the sharpest ones next week.", "Use top questions for TikTok replies; summarize repeated themes in Substack notes.", "founder journey/build-in-public"),
    (12, 5, "TikTok", "TikTok", "The Founder Health Take I Believe More Strongly Now", "The founder health take I believe more strongly now is that systems beat motivation every single time.", "Summarize the evidence from 90 days; tie it to sleep, stress, and recovery; end with a simple principle people can test", "Follow if you want the next experiment from the beginning.", "Reuse as an IG Reel closer; echo the principle in YouTube outro.", "founder journey/build-in-public"),
]


def build_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for week, weekday, platform, content_format, topic_title, hook_line, key_points, cta, repurpose_notes, pillar in ENTRIES:
        current_date = START_DATE + timedelta(days=week * 7 + weekday)
        if current_date > END_DATE:
            raise ValueError(f"Entry out of range: {topic_title} on {current_date.isoformat()}")
        day_number = (current_date - START_DATE).days + 1
        rows.append(
            {
                "date": current_date.isoformat(),
                "day_number": str(day_number),
                "platform": platform,
                "content_format": content_format,
                "topic_title": topic_title,
                "hook_line": hook_line,
                "key_points": key_points,
                "cta": cta,
                "repurpose_notes": repurpose_notes,
                "pillar": pillar,
            }
        )
    rows.sort(key=lambda row: (row["date"], row["platform"], row["topic_title"]))
    return rows


def write_csv(rows: list[dict[str, str]]) -> None:
    with CSV_PATH.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_HEADER)
        writer.writeheader()
        writer.writerows(rows)


def verify_csv() -> int:
    with CSV_PATH.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.reader(handle)
        header = next(reader)
        assert header == CSV_HEADER, f"Header mismatch: {header}"

    with CSV_PATH.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)

    assert 120 <= len(rows) <= 180, f"Unexpected row count: {len(rows)}"

    for row in rows:
        assert set(row.keys()) == set(CSV_HEADER), f"Bad row keys: {row.keys()}"
        assert all(row[column].strip() for column in CSV_HEADER), f"Empty cell found: {row}"
        assert "tbd" not in " ".join(row.values()).lower(), f"TBD found: {row}"
        parsed_date = date.fromisoformat(row["date"])
        assert START_DATE <= parsed_date <= END_DATE, f"Date out of range: {row['date']}"
        expected_day = (parsed_date - START_DATE).days + 1
        assert int(row["day_number"]) == expected_day, f"Bad day number: {row}"
        assert row["platform"] in ALLOWED_PLATFORMS, f"Bad platform: {row['platform']}"
        assert row["pillar"] in ALLOWED_PILLARS, f"Bad pillar: {row['pillar']}"

    return len(rows)


def copy_output() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(CSV_PATH, OUTPUT_PATH)


def main() -> None:
    rows = build_rows()
    write_csv(rows)
    row_count = verify_csv()
    copy_output()
    print(f"Wrote {row_count} rows to {CSV_PATH}")
    print(f"Copied artifact to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
